### ISSUE TITLE
Feature: Front-End Design for Medical Record Pages (User and Admin)

### ISSUE THREAD

**Issue by locks645** [blakep7/medical-portal#7]
**Describe the solution you'd like**
2 webpages (one for both user and admin) that deal with medical records for the patient. Should be done using HTML and CSS with reference to the Figma drawing.

**Additional context**
![Screenshot (175)](https://github.com/blakep7/medical-portal/assets/33185983/6de85216-2b88-4eca-8a5c-dd2ef566cf74)

**Comment by blakep7** [comment]
Closed via #22
