### ISSUE TITLE
Feature: Front-End Design for Payment Page and Log Page (User and Admin)

### ISSUE THREAD

**Issue by StevenKourani** [blakep7/medical-portal#8]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

- Payment Page(User):
  - User will see the items they will be buying and the Subtotal price. 
  - User will also be able to enter Credit card/Debit card information to pay

- Log Page(Admin)
  - Admin will be able to view and see the log of recent patients
  - Admin will also be able to create a log

**Describe alternatives you've considered**
None

**Additional context**
Screenshot of Figma design

**Comment by blakep7** [comment]
Closed via #21
